# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Andrew Flowers
email: andrew.w.flowers@gmail.com
description: Andrew Flowers is a journalist and data scientist. His writing appears at FiveThirtyEight.
# this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://andrewflowers.github.io" # the base hostname & protocol for your site
twitter_username: andrewflowers
github_username:  andrewflowers

# Build settings
markdown: kramdown
